### PR TITLE
[FEATURE] allow to use array in RegisteringNibs

### PR DESCRIPTION
**Pull request by ostk0069**
Hi! I am using this in my company's project!
This is very very comfortable and I love it!

Today, I would like to recommend this function to make this much better.
I think this would make coding faster and nicer.
(I think if this could be okay to merge,  there would be more couple of place to fix.
ex, not only the case with registerNib but register or not only UITableView but UICollectionView and more)

I hope this would make any help. Thanks.

### CODE REVIEW

**Comment by tarunon** [comment]
Thanks propose it!
Is it work correctly? Looks this Array lock in 1 type. Can't pass multiple types this way.🤔

I will check it lator.

**Comment by ostk0069** [comment]
Thanks for your reply.
For this code,  I mean to do it only for registerNib(only when calling Reusable & NibType).
https://github.com/tarunon/Instantiate/blob/9848dd1fbdb00310cc8eae115f2b00c04e485119/Sources/Instantiate/iOS/Reusable%2BUITableView.swift#L45

```
public func registerNib<C: UITableViewCell>(type: C.Type) where C: Reusable, C: NibType {
            register(C.nib, forCellReuseIdentifier: C.reusableIdentifier)
        }
```

if you liked my propose to add this function, I would like to add other function related to this which would pass multiple types.

**Comment by tarunon** [comment]
Hmm, Could you please add test cases for that?
I think I can understand correctly your hope from test cases.

**Comment by tarunon** [comment]
I try to use it, looks not work correctly 🤔 
スクリーンショット 2019-03-22 15 27 09

**Comment by tarunon** [comment]
So, If my understanding is correct, it's really difficult to register them onetime using `Array`.

**Comment by ostk0069** [comment]
Thanks. I got what you meant to say.
Swift Type does not allow us to take more than one.
If I could find the way it works, I will throw another PR again.
Thanks for the conversation.

**Pull request closed without merging**
